### PR TITLE
Fix Changelog.

### LINKED ISSUE #150: Typo in https://mllaunchpad.readthedocs.io/en/stable/changelog.html
### Description

small typo in changelog

### Steps to reproduce
1. Go to: https://mllaunchpad.readthedocs.io/en/stable/changelog.html
2. See title: 1.0.0 (2021-12-13)

should be: 1.1.0 (2021-12-13)
```

### PR DESCRIPTION
**Pull request by TheFenrisLycaon**

### CODE REVIEW

**Comment by TheFenrisLycaon** [comment]
Closes #150

**Review by schuderer — APPROVED** [review]

**Comment by schuderer** [comment]
@TheFenrisLycaon Thanks! Would you like some stickers of our project? I can send you some; I heard people say that they're kind of nice. ;)

**Comment by TheFenrisLycaon** [comment]
@schuderer sure man. I'd love to see them too.

**Comment by schuderer** [comment]
@TheFenrisLycaon Sure! There are still no PMs possible at Github - please contact me at &lt;redacted&gt; and tell me where to send the letter to.

**Comment by TheFenrisLycaon** [comment]
@schuderer, GitHub-Chat sounds like a good idea to me. Lol. I'll send you an email. Thanks again :)

**Pull request merged**
