### PR TITLE
Extend training metadata

### LINKED ISSUE #141: Improve logging and monitoring facilities (ml-ops)
There is a need for more detailed documentation of created models.

Ideally, in a way that is easily customizable by the user.

Current suggestion: extend the model metadata with the required metrics and information.

image

To this end, we will add the two sub-dicts `system` and `train_report` to the metadata. Three mechanisms will be used:

1. More hard-coded info will be added the metadata (Let's keep these as few as possible. See below for details)
2. All keys of the `model` config dict will be added to the metadata (so one can add "description", links to docs, hyper params etc. there and they all will be logged)
3. From code, one can call `mllaunchpad.report("my key name", "my value")`, which causes a key-value pair to be added to subdict `train_report`. This should work inside `create_trained_model` only (in `test_trained_model`, one can simply return the metrics that should be logged).

Elaborating on point 1 above, the things to hard-code are:
- add the `repr()` of the inner model to `train_report`
- add mllp version to `train_report` (and `system`?)
- add IP/name of training machine as `host` to subdict `system`
- add platform to `system`
- add python version to `system`
- add pip freeze result to `system`

Also sensible to provide some API functionality to access the metadata.

### PR DESCRIPTION
**Pull request by schuderer**
Extend metadata resulting from training, closes #141

Tracking the items from the issue:
* [x] All keys of the model config dict will be added to the metadata (so one can add "description", links to docs, hyper params etc. there and they all will be logged)
* [x] From code, one can call mllaunchpad.report("my key name", "my value"), which causes a key-value pair to be added to subdict train_report. This should work inside create_trained_model only (in test_trained_model, one can simply return the metrics that should be logged).

Hard-coded info:
* [x] add the repr() of the inner model to train_report
* [x] add mllp version to ~train_report (and system?)~ system
* [x] add IP and name of training machine as host to subdict system
* [x] add platform to system
* [x] add python version to system
* [x] add pip freeze result to system
* [x] add full config as snapshot instead of only model config

Also:
* [x] Add info about datasources to train_report
* [x] provide some API functionality to access the metadata (more or less optional)

### CODE REVIEW

**Comment by schuderer** [comment]
Update:

I think that this PR is finished (except updating the docs).

All items mentioned in the original post above and the issue #141 should be included (see below for an example metadata json).

The `examples/tree_*` example shows example usage.

- Most info is automatically generated (e.g. system info and the included keys from the `model:` config).
- Adding info dynamically to `train_report` is done using `report("meaning_of_life", 42)` (assuming `report` has been imported from `mllaunchpad`). The key (here "meaning_of_life") is up to the user.
- Summarizing the datasources is, other than originally intended, *not* fully automatic. The reason for this choice is that in order to summarize the data, we need to have it, and it would be potentially very costly to just fetch *all* defined datasources (what if the user sets expires to 0? What if the datasource needs a parameter?). The user can simply choose to call `report` with any dataframe they like. So for example, if I want to log a summary of the training data and already did my `train_df = data_sources["petals"].get_dataframe()`, I just have to do something like `report("train_data_used", train_df )` to log a summary of it. It will end up in the `data` subsection of `train_report`. The key (here "train_data_used") is up to the user.

There is also a function to collect all information on all known models in the model store: `mllaunchpad.list_models()`

```json
{
  "name": "IrisModel",
  "version": "0.0.2",
  "created": "2021-08-31 17:42:45",
  "created_by": "xg12345",
  "system": {
    "mllaunchpad_version": "1.0.0",
    "platform": "Windows-10-10.0.18362-SP0",
    "host": "PCL1234.office01.internalcorp.net",
    "host_ip": "123.123.123.123",
    "python": "3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]",
    "packages": [
      "aniso8601==9.0.1",
      "attrs==21.2.0",
      "click==8.0.1",
      "colorama==0.4.4",
      "dill==0.3.4",
      "Flask==2.0.1",
      "Flask-RESTful==0.3.9",
      "importlib-metadata==4.8.1",
      "itsdangerous==2.0.1",
      "Jinja2==3.0.1",
      "joblib==1.0.1",
      "jsonref==0.2",
      "markdown2==2.4.1",
      "MarkupSafe==2.0.1",
      "mllaunchpad==1.1.0",
      "numpy==1.21.2",
      "pandas==1.3.2",
      "python-dateutil==2.8.2",
      "pytz==2021.1",
      "PyYAML==5.4.1",
      "ramlfications==0.1.9",
      "scikit-learn==0.24.2",
      "scipy==1.7.1",
      "six==1.16.0",
      "termcolor==1.1.0",
      "threadpoolctl==2.2.0",
      "typing-extensions==3.10.0.2",
      "Werkzeug==2.0.1",
      "xmltodict==0.12.0",
      "zipp==3.5.0"
    ]
  },
  "train_report": {
    "meaning_of_life": 42,
    "data": {
      "train_data_used": {
        "nrows": 130,
        "ncols": 5,
        "colnames": [
          "sepal.length",
          "sepal.width",
          "petal.length",
          "petal.width",
          "variety"
        ],
        "dtypes": [
          "float64",
          "float64",
          "float64",
          "float64",
          "object"
        ],
        "description": {
          "sepal.length": {
            "count": 130.0,
            "mean": 5.841538461538461,
            "std": 0.8114285054393119,
            "min": 4.3,
            "25%": 5.1,
            "50%": 5.8,
            "75%": 6.4,
            "max": 7.7
          },
          "sepal.width": {
            "count": 130.0,
            "mean": 3.074615384615385,
            "std": 0.434431204081047,
            "min": 2.2,
            "25%": 2.8,
            "50%": 3.0,
            "75%": 3.375,
            "max": 4.4
          },
          "petal.length": {
            "count": 130.0,
            "mean": 3.7546153846153842,
            "std": 1.7652595627251215,
            "min": 1.0,
            "25%": 1.6,
            "50%": 4.4,
            "75%": 5.1,
            "max": 6.9
          },
          "petal.width": {
            "count": 130.0,
            "mean": 1.2061538461538461,
            "std": 0.768745464084819,
            "min": 0.1,
            "25%": 0.3,
            "50%": 1.3,
            "75%": 1.8,
            "max": 2.5
          }
        }
      },
      "test_data_used": {
        "nrows": 20,
        "ncols": 5,
        "colnames": [
          "sepal.length",
          "sepal.width",
          "petal.length",
          "petal.width",
          "variety"
        ],
        "dtypes": [
          "float64",
          "float64",
          "float64",
          "float64",
          "object"
        ],
        "description": {
          "sepal.length": {
            "count": 20.0,
            "mean": 5.855,
            "std": 0.9522687590558057,
            "min": 4.4,
            "25%": 5.0,
            "50%": 5.95,
            "75%": 6.4,
            "max": 7.9
          },
          "sepal.width": {
            "count": 20.0,
            "mean": 2.945,
            "std": 0.43946738098221627,
            "min": 2.0,
            "25%": 2.8,
            "50%": 2.95,
            "75%": 3.125,
            "max": 3.8
          },
          "petal.length": {
            "count": 20.0,
            "mean": 3.78,
            "std": 1.8112513848020568,
            "min": 1.2,
            "25%": 1.5,
            "50%": 4.1,
            "75%": 5.075,
            "max": 6.4
          },
          "petal.width": {
            "count": 20.0,
            "mean": 1.1549999999999998,
            "std": 0.7359025965295594,
            "min": 0.1,
            "25%": 0.2,
            "50%": 1.35,
            "75%": 1.8,
            "max": 2.2
          }
        }
      }
    },
    "awesomest_number": 300000,
    "algorithm": "DecisionTreeClassifier()"
  },
  "metrics": {
    "accuracy": 0.9,
    "confusion_matrix": [
      [
        6,
        0,
        0
      ],
      [
        0,
        6,
        1
      ],
      [
        0,
        1,
        6
      ]
    ]
  },
  "metrics_history": {
    "2021-08-31 17:42:47": {
      "accuracy": 0.9,
      "confusion_matrix": [
        [
          6,
          0,
          0
        ],
        [
          0,
          6,
          1
        ],
        [
          0,
          1,
          6
        ]
      ]
    },
    "2021-08-31 17:44:12": {
      "accuracy": 0.9,
      "confusion_matrix": [
        [
          6,
          0,
          0
        ],
        [
          0,
          6,
          1
        ],
        [
          0,
          1,
          6
        ]
      ]
    },
    "2021-08-31 17:45:04": {
      "accuracy": 0.9,
      "confusion_matrix": [
        [
          6,
          0,
          0
        ],
        [
          0,
          6,
          1
        ],
        [
          0,
          1,
          6
        ]
      ]
    },
    "2021-08-31 17:45:22": {
      "accuracy": 0.9,
      "confusion_matrix": [
        [
          6,
          0,
          0
        ],
        [
          0,
          6,
          1
        ],
        [
          0,
          1,
          6
        ]
      ]
    }
  },
  "config_snapshot": {
    "plugins": [
      "examples.bogusdatasource"
    ],
    "datasources": {
      "petals": {
        "type": "csv",
        "path": "./iris_train.csv",
        "expires": 0,
        "options": {},
        "tags": "train"
      },
      "petals_test": {
        "type": "csv",
        "path": "./iris_holdout.csv",
        "expires": 3600,
        "options": {},
        "tags": "test"
      },
      "batch_input": {
        "type": "csv",
        "path": "./iris_pred_input.csv",
        "expires": 3600,
        "options": {},
        "tags": "predict"
      },
      "blabla": {
        "type": "bogus"
      }
    },
    "datasinks": {
      "predictions": {
        "type": "csv",
        "path": "./iris_pred_output.csv",
        "options": {},
        "tags": [
          "predict"
        ]
      }
    },
    "model_store": {
      "location": "./model_store"
    },
    "model": {
      "name": "IrisModel",
      "version": "0.0.2",
      "module": "tree_model",
      "train_options": {},
      "predict_options": {}
    },
    "api": {
      "name": "iris",
      "raml": "tree.raml",
      "preload_datasources": true,
      "root_path": "."
    }
  },
  "api_base_url": "/iris/v0",
  "train_options": {},
  "predict_options": {}
}
```

**Comment by Vegacyrez** [comment]
Thanks for this update, I think it will greatly support MLOPS using MLLP! A suggestion: in the future it could be useful to force some of these fields that are not automatically generated to be mandatory during the deployment process as a way to guarantee a proper audit trail.

**Comment by schuderer** [comment]
> Thanks for this update, I think it will greatly support MLOPS using MLLP! A suggestion: in the future it could be useful to force some of these fields that are not automatically generated to be mandatory during the deployment process as a way to guarantee a proper audit trail.

Thanks, great to hear it! :) Interesting suggestion to enforce some values. To me, this seems to be more related to the build/delivery pipeline (like e.g. vulnerability scans, see the mllaunchpad-template repo for an example). Technically, it would be possible to do at least some enforcing based on information on e.g. some additional section of the config. We do some of that (albeit not configurable) on the config itself. If you're interested how this could work, have a look at the config module of the mllp code.

If this is not a strict requirement for this PR to be useful, however, I suggest I'll merge it as-is.

**Comment by schuderer** [comment]
PS: Regarding some questions/issues:

 - Ordering: The order of the keys in the resulting JSON structure follows the order in which they are added to the underlying dict. So the ordering of some groups can be influenced (e.g. order of keys in the `model:` config, order of calls to `report()`), while that of others cannot.
 - While it's technically possible to use `report()` in your testing function, it is preferable to put any test-related results you'd like to persist into the returned metrics. It is therefore recommended to make the value returned from the testing function a `dict`.
 - If you want to persist an example prediction result, I'd add it to the returned metrics of your testing function with a dict key like e.g. `prediction_example`).
 - `report()` is also able to persist simple data structures like `dict`s, `list`s, small numpy arrays, etc.
 - If your config gets ling and unwieldy, you can use !include <file.yml> to modularize it.

**Pull request merged**
