### PR TITLE
add optional addition of Flask host and port

### PR DESCRIPTION
**Pull request by maxxiefjv**
#### What this implements/fixes
Very straight forward implementation to optionally configure HOST and PORT to run the application on

### CODE REVIEW

**Comment by schuderer** [comment]
Thanks for the PR @maxxiefjv!

Before we continue with the PR: I just now came to realize that one motivation for using another port might be production/integration requirements. Please be advised that [the command](https://mllaunchpad.readthedocs.io/en/stable/usage.html?highlight=debug#mllaunchpad-api) `mllaunchpad api [OPTIONS]` is meant for debugging only. For production/deployment, use a WSGI server like waitress or uWSGI.

This makes me wonder why you feel the need to specify a host and port in the configuration -- the configuration settings are not exactly debugging-related. And any host and port specified there would be ignored in a production situation because the flask debug mode would not be used there (those would fall into the realm of the WSGI server). Users might overlook this fact and wonder why their api host/port settings are suddenly ignored.

Not saying that it doesn't make any sense whatsoever, just that as it sounds to me, a CLI parameter looks like a better spot for something like this. Could you help me understand the rationale/problem behind the PR?

From the standpoint of PR handling, I fixed some stuff on the main branch, so it now makes sense to pull from master. The only thing that are missing formally are docs and the changelog.

**Comment by schuderer** [comment]
Another idea: maybe calling the options "debug-..." would be a compromise? That would make their purpose clear, without needing to specify CLI options on every call.

**Comment by maxxiefjv** [comment]
I'm OK 'debug-port' and 'debug-host', although I doubt it necessary. A very reasonable explanation for wanting to change ports locally, is that port 5000 is a very default port when writing applications. Meaning that as soon as you want to run more than 1 service locally, chances are very likely that port 5000 is already in use. 

For that reason alone I think we should progress with this PR, this is a must have regardless of the DEV/TEST/ACC/PROD environment one is working in. (Moreover, there is a clear Flask warning on how to run the service in a PROD environment)

I will update the PR, to adjust the naming.

**Comment by schuderer** [comment]
Thanks. It was mostly the rationale behind the host option which was puzzling me a bit, but doesn't matter: 'debug-port' and 'debug-host' will be fine. Please don't forget to document them in the docs and add your change to the changelog, and run `nox` locally before pushing (see contributing guide for details).

**Comment by schuderer** [comment]
Thanks. It seems the CI is still on the old state for this PI. Could you please pull from upstream master and think of the docs/changelog? Thanks

**Comment by schuderer** [comment]
Maybe to clarify my initial statement: There are other ways to run it on a different port and/or network device, if that is all you need. First of all, you can use a proper WSGI server (needed for, but not exclusive to, production use). For example, this works on Windows:
```
pip install waitress
waitress-serve --listen=localhost:1234 mllaunchpad.wsgi:application
```
You can use any other WSGI server. Another example (Linux/macOS):
```
pip install gunicorn
gunicorn -b 127.0.0.1:8000 mllaunchpad.wsgi:application
```

If you really need to use Flasks debug mode for your integration tests, [this is also possible](https://flask.palletsprojects.com/en/2.1.x/cli), e.g.:
```
set LAUNCHPAD_CFG=my_cfg.yml
set FLASK_APP=mllaunchpad.wsgi:application
set FLASK_ENV=development
python -m flask run --host localhost --port 1234
```

**Pull request closed without merging**
